import { NextResponse } from 'next/server';

export async function GET() {
    // Mock Data for Santa Cruz Trails
    const trails = [
        {
            id: '1',
            name: 'Pogonip Creek Nature Loop',
            summary: 'Beautiful shaded trail near UCSC.',
            difficulty: 'Easy',
            stars: 4.5,
            latitude: 37.0050,
            longitude: -122.0450,
            length: 3.5,
            url: 'https://www.hikingproject.com/trail/12345/pogonip',
            imgSqSmall: '',
        },
        {
            id: '2',
            name: 'U-Con Trail',
            summary: 'Popular connector for bikers and hikers.',
            difficulty: 'Intermediate',
            stars: 4.8,
            latitude: 37.0000,
            longitude: -122.0530,
            length: 2.1,
            url: '',
            imgSqSmall: '',
        },
        {
            id: '3',
            name: 'Old Growth Loop',
            summary: 'See the giant redwoods.',
            difficulty: 'Easy',
            stars: 5.0,
            latitude: 37.0120,
            longitude: -122.0550,
            length: 1.2,
            url: '',
            imgSqSmall: '',
        },
        {
            id: '4',
            name: 'Wilder Ranch Coastal Trail',
            summary: 'Stunning ocean views.',
            difficulty: 'Intermediate',
            stars: 4.9,
            latitude: 36.9600,
            longitude: -122.0830,
            length: 4.5,
            url: '',
            imgSqSmall: '',
        },
        {
            id: '5',
            name: 'DeLaveaga Park Loop',
            summary: 'Disc golf and nice woods.',
            difficulty: 'Easy',
            stars: 4.2,
            latitude: 37.0150,
            longitude: -122.0100,
            length: 2.5,
            url: '',
            imgSqSmall: '',
        },
        {
            id: '6',
            name: 'West Crack (MTB)',
            summary: 'Technical downhill track.',
            difficulty: 'Advanced',
            stars: 4.7,
            latitude: 37.0020,
            longitude: -122.0680,
            length: 1.0,
            url: '',
            imgSqSmall: '',
        },
        {
            id: '7',
            name: 'Garden of Eden',
            summary: 'Popular swimming hole trail.',
            difficulty: 'Moderate',
            stars: 4.6,
            latitude: 37.0300,
            longitude: -122.0580,
            length: 1.5,
            url: '',
            imgSqSmall: '',
        },
        {
            id: '8',
            name: 'Top of the World',
            summary: 'Best sunset spot.',
            difficulty: 'Intermediate',
            stars: 4.8,
            latitude: 37.0100,
            longitude: -122.0300,
            length: 0.8,
            url: '',
            imgSqSmall: '',
        },
    ];

    return NextResponse.json({ trails });
}
